### ISSUE TITLE
grep:  No such file or directory

### ISSUE THREAD

**Issue by metalichen** [stajichlab/FGMP#14] opened 2019-09-14 01:13 UTC
Hi,

I installed the package via git clone. When I tried to run it on the sample data, I got an error:

```
[ 12-09-2019 04:20:35 PM ]      file: /path/FGMP/data/593_cleanMarkers.hmm.gz is already decompressed - good!
[ 12-09-2019 04:20:35 PM ]      Finding candidate regions
[ 12-09-2019 04:34:24 PM ]  Refining mapping on candidate regions
[ 12-09-2019 04:34:24 PM ]      Mapping proteins to assembly chunks using Exonerate
[ 12-09-2019 04:34:52 PM ]      Training Augustus
grep: sample/sample_test.dna.trainingSet.gb: No such file or directory
Argument "" isn't numeric in numeric ge (>=) at src/fgmp.pl line 252.
```

I commented the lines 328 to 331 of the fgmp.pl to check whether the file sample_test.dna.trainingSet.gb is produced, and it is there. I was not able to figure out while grep cannot find it

**Comment by ocisse** [comment] 2019-11-20 20:36
Sorry for the late reply. Just move the sample_test.dna in the current dir and re-run it. 

Thanks for using FGMP

**Comment by metalichen** [comment] 2019-12-16 18:33
Hi, I did that and still got the same error
```
[ 16-12-2019 11:15:34 AM ]      file: /scratch/1/gulnara/soft/FGMP/data/593_cleanMarkers.hmm.gz is already decompressed - good!
[ 16-12-2019 11:15:34 AM ]      Finding candidate regions
[ 16-12-2019 11:30:05 AM ]      Refining mapping on candidate regions
[ 16-12-2019 11:30:05 AM ]      Mapping proteins to assembly chunks using Exonerate
[ 16-12-2019 11:30:35 AM ]      Training Augustus
grep: ./sample_test.dna.trainingSet.gb: No such file or directory
Argument "" isn't numeric in numeric ge (>=) at ./src/fgmp.pl line 252.
```

**Comment by metalichen** [comment] 2019-12-16 19:01
I did that, and got a different error:
```
>./src/fgmp.pl -g sample_test.dna -T 10 --tag OMA
[ 16-12-2019 11:36:03 AM ]      file: /scratch/1/gulnara/soft/FGMP/data/593_cleanMarkers.hmm.gz is already decompressed - good!
[ 16-12-2019 11:36:03 AM ]      Finding candidate regions
[ 16-12-2019 11:53:48 AM ]      Refining mapping on candidate regions
[ 16-12-2019 11:53:48 AM ]      Mapping proteins to assembly chunks using Exonerate
[ 16-12-2019 11:54:17 AM ]      Training Augustus
size 50 is greater than the number of genes in file
sample_test.dna.trainingSet.gb. Aborting.

cannot execute  etraining --species=sample_test.dna sample_test.dna.trainingSet.gb.train --AUGUSTUS_CONFIG_PATH=/scratch/1/gulnara/soft/FGMP/augustus_tmp/config > /dev/null 2>&1:No such file or directory
 at ./src/fgmp.pl line 267.
```

**Comment by ocisse** [comment] 2019-12-16 20:08
Something wrong with the file. Might be it's empty or damaged. Alternatively, can you grab a fungal genome from NCBI and re-run it? I couldn't reproduce this error.

**Comment by metalichen** [comment] 2019-12-17 18:11
I did that and weirdly enough got the old grep issue as before, even though the fasta file is in the current folder
```
 ./src/fgmp.pl -g Cryne_JEC21_1_AssemblyScaffolds.fasta -T 10 --tag OMA
[ 17-12-2019 10:39:31 AM ]      file: /scratch/1/gulnara/soft/FGMP/data/593_cleanMarkers.hmm.gz is already decompressed - good!
[ 17-12-2019 10:39:31 AM ]      Finding candidate regions
[ 17-12-2019 10:53:54 AM ]      Refining mapping on candidate regions
[ 17-12-2019 10:53:54 AM ]      Mapping proteins to assembly chunks using Exonerate
[ 17-12-2019 11:03:07 AM ]      Training Augustus
grep: Cryne_JEC21_1_AssemblyScaffolds.fasta.trainingSet.gb: No such file or directory
Argument "" isn't numeric in numeric ge (>=) at ./src/fgmp.pl line 252.
[ 17-12-2019 11:03:08 AM ]      Insufficient number of genes for augustus training :-(
Skip Augustus step
```

**Comment by ocisse** [comment] 2019-12-17 21:03
5280 $ perl src/fgmp.pl -g GCF_000149245.1_CNA3_genomic.fna -T 8 --tag OMA
[ 17-12-2019 03:35:37 PM ]	file: /hpcdata/dcr_cc/Ousmane_Data/projects/FGMP/TESTs/191217/FGMP/data/593_cleanMarkers.hmm.gz is already decompressed - good!
[ 17-12-2019 03:35:37 PM ]	Finding candidate regions
[ 17-12-2019 03:35:49 PM ]	Refining mapping on candidate regions
[ 17-12-2019 03:35:51 PM ]	Training Augustus
[ 17-12-2019 03:36:06 PM ]	Running Augustus
[ 17-12-2019 03:44:14 PM ]	Merging translated CDS and augustus predictions
[ 17-12-2019 03:44:14 PM ]	2558 predictions to compare to HMM models
[ 17-12-2019 03:44:14 PM ]	Filtering gene models
[ 17-12-2019 03:47:47 PM ]	Loading profiles
[ 17-12-2019 03:47:48 PM ]	Loading markers
[ 17-12-2019 03:47:48 PM ]	Loading model data
[ 17-12-2019 03:47:48 PM ]	Analyzing output
[ 17-12-2019 03:51:23 PM ]	Selecting best candidate per locus
[ 17-12-2019 03:54:08 PM ]	Tracking abberant gene models
[ 17-12-2019 03:54:08 PM ]	COMPLETENESS ESTIMATION
[ 17-12-2019 03:54:08 PM ]	Job completion log: 1 / 460 done
....
[ 17-12-2019 03:54:08 PM ]	Job completion log: 460 / 460 done
[ 17-12-2019 03:54:08 PM ]	DONE!
[ 17-12-2019 03:54:08 PM ]	Printing full report
[ 17-12-2019 03:54:08 PM ]	Printing summary report

**Comment by ocisse** [comment] 2019-12-17 21:05
I cannot reproduce your error, but I suspect your issue is related to augustus installation. If your "Cryne_JEC21_1_AssemblyScaffolds.fasta.trainingSet.gb" is not created, might some of augustus auxiliary scripts are not working properly. Please check your installation. Thx

**Comment by ocisse** [comment] 2019-12-31 20:52
I think the problem is caused by Augustus scripts (e.g. etraining). I am closing the issue but feel free to open a new one if the problem persists. Thanks

**Closed as completed by ocisse** 2019-12-31 20:52 UTC
