### ISSUE TITLE
Issues with Conda installation

### ISSUE THREAD

**Issue by emmannaemeka** [stajichlab/FGMP#15] opened 2019-11-19 18:25 UTC
emmannadi$ conda install -c bioconda fgmp
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - fgmp -> augustus[version='>=3.2.3'] -> boost[version='>=1.70.0,<1.70.1.0a0']
  - fgmp -> augustus[version='>=3.2.3'] -> gsl[version='>=2.5,<2.6.0a0']
  - fgmp -> augustus[version='>=3.2.3'] -> libcblas[version='>=3.8.0,<4.0a0']
  - fgmp -> augustus[version='>=3.2.3'] -> lp_solve
  - fgmp -> augustus[version='>=3.2.3'] -> suitesparse[version='>=4.5.6,<5.0a0']

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by ocisse** [comment] 2019-11-20 20:30
which conda version do you have? Conda doesn’t seems to support Augustus v3.2.3 or at least some of its dependencies. Unfortunately, the v3.3.3 currently hosted in conda doesn't work well with FGMP. Try to install FGMP manually  or try to install each of the dependencies.

Let me know how it went. Thanks for using FGMP

**Comment by emmannaemeka** [comment] 2019-11-22 15:18
Getting Augustusv3.2.3 I found this link helpful
osx-64/augustus-3.2.3-pl526hcfae127_5.tar.bz2
<https://anaconda.org/bioconda/augustus/3.2.3/download/osx-64/augustus-3.2.3-pl526hcfae127_5.tar.bz2>
 //
anaconda.org/bioconda/augustus/3.2.3/download/osx-64/augustus-3.2.3-pl526hcfae127_5.tar.bz2
Nnadi Nnaemeka Emmanuel,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:
 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by ocisse** [comment] 2019-12-31 20:53
I think the problem is caused by Augustus installation. I am closing the issue but feel free to open a new one if the problem persists. Thanks

**Closed as completed by ocisse** 2019-12-31 20:53 UTC
